// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "TURKEY":return img`
................................
................................
................................
................................
................................
................................
................................
..................ccc...........
..............cccc444f..........
.............c44444444f.........
............c444444444f.........
..........ccc444444444f.........
........cc4444444444444f........
......cceee444444444444f........
....cc44eef1f4444444444f........
...cbbb44efffef444444ff.........
....ffff4efffef444444f..........
......2feeeeeeeffffff...........
.....22feeeeeebff...............
.....2ffeeeeeebefff.............
......feeeeeeebeeeecc...........
.....cceeeeeeebeeeeeec..........
.....ceeeeeeeebeeeeeeec.........
.....ceeeeeeeebeeeeeebcc........
.....ceeeeeeeebeeeeebbeec.......
.....ceeeeeeeebbeeebbeeebc......
......ceeeeeeeebbebbeeeebbccc...
......cceeeeeeeebbbbcccccbbbcc..
.......cceeeeeeeeeeeeeebccffff..
........cccbeeccbeeeebbfff......
........c333bb333cbbfff.........
........c33cc33cc3fff...........
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
